#ifndef TERMMAN_LEVEL_DEFS_H
#define TERMMAN_LEVEL_DEFS_H

#include "std_objects.h"

terrain_t level[MAX_Y][MAX_X] = {
	{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL },
	{ WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, WALL, FREE, FREE, WALL, FOOD, WALL, FREE, FREE, FREE, WALL, FOOD, WALL, WALL, FOOD, WALL, FREE, FREE, FREE, WALL, FOOD, WALL, FREE, FREE, WALL, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL },
	{ WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, PATH, WALL, WALL, PATH, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL },
	{ FREE, FREE, FREE, FREE, FREE, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, PATH, WALL, WALL, PATH, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, FREE, FREE, FREE, FREE, FREE },
	{ FREE, FREE, FREE, FREE, FREE, WALL, FOOD, WALL, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, WALL, FOOD, WALL, FREE, FREE, FREE, FREE, FREE },
	{ FREE, FREE, FREE, FREE, FREE, WALL, FOOD, WALL, WALL, PATH, WALL, WALL, WALL, GATE, GATE, WALL, WALL, WALL, PATH, WALL, WALL, FOOD, WALL, FREE, FREE, FREE, FREE, FREE },
	{ WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, PATH, WALL, FREE, FREE, FREE, FREE, FREE, FREE, WALL, PATH, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL },
	{ PATH, PATH, PATH, PATH, PATH, PATH, FOOD, PATH, PATH, PATH, WALL, FREE, FREE, FREE, FREE, FREE, FREE, WALL, PATH, PATH, PATH, FOOD, PATH, PATH, PATH, PATH, PATH, PATH },
	{ WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, PATH, WALL, FREE, FREE, FREE, FREE, FREE, FREE, WALL, PATH, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL },
	{ FREE, FREE, FREE, FREE, FREE, WALL, FOOD, WALL, WALL, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, WALL, WALL, FOOD, WALL, FREE, FREE, FREE, FREE, FREE },
	{ FREE, FREE, FREE, FREE, FREE, WALL, FOOD, WALL, WALL, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, PATH, WALL, WALL, FOOD, WALL, FREE, FREE, FREE, FREE, FREE },
	{ FREE, FREE, FREE, FREE, FREE, WALL, FOOD, WALL, WALL, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, WALL, WALL, FOOD, WALL, FREE, FREE, FREE, FREE, FREE },
	{ WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, PATH, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, PATH, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL },
	{ WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, PATH, PATH, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, WALL },
	{ WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL },
	{ WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL },
	{ WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, WALL, WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL, WALL, FOOD, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, FOOD, WALL },
	{ WALL, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, FOOD, WALL },
	{ WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL }
};

#endif
